### ISSUE TITLE
lincom

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#15]
It would be very useful if lincom could handle lm objects as well as uRegress objects

**Comment by cwolock** [comment]
@jphughes9 How high of a priority is this for you? I have `lincom` in good working order for `uRegress` objects at the moment. If this is something we want for fall quarter, then I will try to get it done in the next couple weeks - otherwise I might be inclined to wait until we release a second version of the package.

**Comment by jphughes9** [comment]
Charlie

I will not use lincom in the fall so it could wait for further improvements

Jim
--------------
Jim Hughes
Professor of Biostatistics
University of Washington           Email: ***@***.******@***.***>
Mailstop 351617                           Phone: 206-616-2721
Seattle, WA  98195                        Fax:      206-616-2724
                                                          Cell:      206-498-2456
