### ISSUE TITLE
what is 'stratify' supposed to do in bplot?

### ISSUE THREAD

**Issue by taylorokonek** [statdivlab/rigr#28]
I can't seem to get an example working (that doesn't throw an error) where the 'strata' argument in bplot is used. Is this argument supposed to do something analogous to facet_wrap in ggplot, or something else?

**Comment by bdwilliamson** [comment]
If memory serves, "strata" is supposed to work in a similar fashion to `ggplot2::facet_wrap`. We could turn `bplot` into a wrapper for geom_boxplot, where we have "simpler" arguments and include jittered data by default?

**Comment by taylorokonek** [comment]
I like that idea! I'm always down to ggplot-ify things. I'll work on getting a new version of bplot working that's a bit simplified and uses geom_boxplot

**Comment by bdwilliamson** [comment]
Several other features that might be nice (trying to match this [doc](http://www.emersonstatistics.com/GeneralMaterials/R/fevdoc.html#box-plots):
- using theme_bw() by default
- putting the facets in the same plot window (since ultimately, the goal with bplot was to allow an arbitrary number of strata, even though in the doc I linked to we only considered a "standard" boxplot)
- option to overlay the mean +/- SD
