### ISSUE TITLE
descrip no longer works is intended on `mri` data

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#3]
A previous line in `test_cases` vignette was `descrip(mri)`. This no longer works. Possible reasons include that `mri` is now a tibble rather than a dataframe, but perhaps also because it contains variables of different types (not only numeric).

**Comment by bdwilliamson** [comment]
I'll handle this one!

**Comment by bdwilliamson** [comment]
Fixed in 0e69fcb. The error was due to R no longer reading in strings as factors by default (this may be the only place where that caused an error!). `descrip` expected a factor variable, so when it saw a character variable, it failed.

In the above commit, I have also split out the helper functions that used to live within `descrip` into `R/descrip_helpers.R`. Should have made a PR -- next time!
