### ISSUE TITLE
Wilcoxon bug

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#48]
[Wilcoxon bug.docx](https://github.com/statdivlab/rigr/files/6942075/Wilcoxon.bug.docx)

**Comment by cwolock** [comment]
Thanks for pointing this out. The labeling issue is known - see #31. That's on my to-do list. I'll try to figure out the issue with number of observations, rank-sum, etc.

**Comment by cwolock** [comment]
From Jim: 

Notice the number of observations, rank sum and expected are incorrect for X below. Also, it would be nice if the program used labels “seropos” and “seroneg” instead of X and Y.

seropos = c(2.9,12.1,2.6,2.5,2.8,15.8,3.2,1.8,7.8,2.9,3.2,8.0,1.5,6.3,1.2,3.5)
seroneg = c(4.5,1.3,1.0,1.0,1.3,1.9,1.3,2.1,2.1,1.0)
wilcoxon(seropos,seroneg)

 Wilcoxon rank sum test 
         obs rank sum expected
Y         16      273    175.5
X         16      273    175.5
combined  32      546    351.0
                               
unadjusted variance 360.0000000
adjustment for ties   0.1015385
adjusted variance   359.8984615
                    H0 Ha       
Hypothesized Median 0  two.sided
  Test Statistic p-value 
W 137            0.002614
Z 3.0098         0.002614

**Comment by cwolock** [comment]
The labeling issue still exists in #31. The other bug should be fixed by 097ee0d99b45d9043c32083120c23d8db5676e8e. Among other issues, it seems like `wilcoxon` actually had the wrong formula for calculating the expected rank sums. @jphughes9 let me know if this works correctly for you now.

**Comment by cwolock** [comment]
The data name fix was easier than expected - should be fixed by b9360b4591d588218af98c1341bb858c9954e874. Let me know if it seems to be working for you.
