### ISSUE TITLE
bug in wilcoxon

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#9]
one-sided p-value in wilcoxon wrong . Fixed in the attached file. Search for "JPH" to find changes
[my_wilcoxon.txt](https://github.com/statdivlab/rigr/files/6353531/my_wilcoxon.txt)

**Comment by cwolock** [comment]
I am in the process of making this fix, per the code provided by @jphughes9. Jim, I'm wondering if maybe there's one more spot in the code where that bug exists - line 420 in your file. Should that also be changed?

**Comment by jphughes9** [comment]
Charlie

Oh, yes, good catch.

Jim
--------------
Jim Hughes
Professor of Biostatistics
University of Washington           Email: ***@***.******@***.***>
Mailstop 351617                           Phone: 206-616-2721
Seattle, WA  98195                        Fax:      206-616-2724
                                                          Cell:      206-498-2456

**Comment by cwolock** [comment]
Thank Jim. Along these lines - is there a reason that we re-calculate the p-value in that block of code for the `inf` object? As far as I can tell, the p-value is already calculated above, for example in line 188 in the current version of `wilcoxon.R` on github.

**Comment by jphughes9** [comment]
I didn't really analyze the code that closely ... just put in fixes where there were errors. I seemed like the PVAL computed around line 188 wasn't getting used everywhere

**Comment by cwolock** [comment]
Okay, that's good to know. I'll go ahead and take the liberty of simplifying the code if possible...I believe the PVAL in line 188 is actually what's reported in the `p.value` object in the results, and the p-value that you fixed appears only in the `inf` object. To be honest, I'm not really sure why `inf` exists other than to report the z-score. 

In either case, I think for future maintenance I think we want to streamline this whole thing. I'll close this issue since I fixed the specific problem and make a new issue to get rid of the redundancies.

**Comment by jphughes9** [comment]
Well, I think I recall that the wrong p-value was sometimes reported in the results (maybe I’m misremembering)

Jim
--------------
Jim Hughes
Professor of Biostatistics
University of Washington           Email: ***@***.******@***.***>
Mailstop 351617                           Phone: 206-616-2721
Seattle, WA  98195                        Fax:      206-616-2724
                                                          Cell:      206-498-2456

**Comment by cwolock** [comment]
Yes, you're right - the p-value you corrected comes out in the `inf` object. The `PVAL` p-value comes out in the `p.value` object. So when the bug was present you could get two different p-values in the output.
