### ISSUE TITLE
Deletion diagnostics? 

### ISSUE THREAD

**Issue by lytinoue** [statdivlab/rigr#97]
I would like to suggest including deletion diagnostics with measures such delta-beta (unstandardized or standardized), Cook's distance, etc, available under lm and glm (see https://stat.ethz.ch/R-manual/R-devel/library/stats/html/influence.measures.html).

**Comment by adw96** [comment]
Hi @lytinoue - I have implementations of `residuals`, `rstandard`, `rstudent`, `dfbeta`, `dfbetas`, `cooks.distance` and `hatvalues` working well 🥳 (This was surprisingly easy thanks to the hard work of Charlie and Taylor!) No documentation yet, though. 

It's going to take a little bit more work for me to get `covratio()`, `dffits()` and `influence.measures()` together. Can I confirm that you would use these last 3 functions if I implemented them? 

I will push all of the working functions later today. 

Cheers, 

Amy

**Comment by adw96** [comment]
Now pushed to branch [diagnostics](https://github.com/statdivlab/rigr/tree/diagnostics) if you want to play with it there (commit 776d764)

**Comment by adw96** [comment]
From @lytinoue via email: 

> Anyway, what you implemented is perfect! Yay! I don't need covratio(), dffits() and things in influence.measures().

A brief summary of updates

- S3 implementations for `rstandard`, `rstudent`, `dfbeta`, `dfbetas`, `cooks.distance`, `hatvalues` for objects of class `uRegress `
- `test_that()` tests that confirm that `dfbeta`, `dfbetas`, `cooks.distance` and `hatvalues` match the output of an equivalent `lm()` model (this is true because the estimated coefficients (and therefore also fitted values) shouldn't change between these two models)
- `test_that()` tests that confirm that `rstandard` and `rstudent` are perfectly correlated with their equivalent from `lm()` model (which is to be expected because the residual standard error is different between the robust and non-robust implementations)
- Documentation for the new functions

Important: My checks only check `fnctl = "mean"`. I've done no such checks for `fnctl = "odds"`, etc. 

Closing this issue since these commits address the initial request. Happy deletion-diagnosing, all! 😸 🎁
